model:
  d_fft: 1024
  d_model: 512
  dropout: 0.1
  heads: 4
  layers: 6
  type: transformer
paths:
  checkpoint_dir: checkpoints
  data_dir: datasets
preprocessing:
  char_repeats: 3
  languages:
  - en-us
  lowercase: true
  n_val: 1
  phoneme_symbols:
  - au
  - bha
  - aa
  - ra
  - na
  - ga
  - ah
  - ii
  - kha
  - pha
  - Ta
  - ha
  - chhya
  - sa
  - gyah
  - an
  - ahDa
  - tha
  - ba
  - sha
  - trah
  - e
  - Dha
  - Sa
  - da
  - nga
  - gha
  - ri
  - dha
  - Da
  - chha
  - pa
  - ma
  - ya
  - aah
  - la
  - i
  - wa
  - ai
  - ja
  - cha
  - jha
  - oo
  - ka
  - u
  - o
  - ta
  - Tha
  text_symbols: "\u0905\u0906\u0907\u0908\u0909\u090A\u090F\u0910\u0913\u0914\u090B\
    \u0905\u0902\u0905\u0903\u0915\u0916\u0917\u0918\u0919\u091A\u091B\u091C\u091D\
    \u091E\u091F\u0920\u0921\u0922\u0923\u0924\u0925\u0926\u0927\u0928\u092A\u092B\
    \u092C\u092D\u092E\u092F\u0930\u0932\u0935\u0936\u0937\u0938\u0939\u0915\u094D\
    \u0937\u0924\u094D\u0930\u091C\u094D\u091E"
training:
  batch_size: 1
  batch_size_val: 1
  checkpoint_steps: 100000
  epochs: 20
  generate_steps: 500
  learning_rate: 0.0001
  n_generate_samples: 10
  scheduler_plateau_factor: 0.5
  scheduler_plateau_patience: 10
  store_phoneme_dict_in_model: true
  test_steps: 500
  validate_steps: 500
  warmup_steps: 100
